name: 02-events-workflow
on: 
    pull_request :
    push: 
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:     
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name : show the trigger
              run: 
                echo this is the firstep and the event name ${{github.event_name}}
