name: 04-actions-workflow
on: push

jobs:
   build:
    runs-on: ubuntu-22.04
    defaults:
      run : 
        working-directory: 04-using-actionsß
    steps:
       - name: checkout the code
         uses: actions/checkout@v4
       - name: install node
         uses: actions/setup-node@v3
         with:
           node-version: '20.x'
       - name: Install-Dependecies
         run : npm ci
       - name: run the unit test
         run : npm run test
         